### ISSUE TITLE
CrowdAI @ PyData-Zurich

### ISSUE THREAD

**Issue by spMohanty** [pydatazrh/meetup#4]
If theres scope for round table discussions, would love to discuss whats the best way to create resources to help people get started with Data Science (by stripping out the scary technicalities like in the sklearn/tflearn-approach or help them instead develop an intuition behind these approaches or both).

And how to convince new learners to propagate the knowledge by creating more learning content as they learn !!

**Comment by betatim** [comment]
I'm not sure what exactly you'd want to present/talk about ;)

There is already a lot of great content out there for people to learn about both data science and machine-learning. Not sure more content is needed.

Status: confused.com

**Comment by TitusCornelius** [comment]
hey SpMohanty, we appreciate your spirit of participation!

As I see it, this thread does not lead yet to any constructive next steps that we can actually execute right now. If you have any more concrete suggestions for speakers or a (very) specific topic, please post it in the 'topics or talks'. That's also why I had to close this issue, as otherwise it would clutter our issues section even though topics should be centrally discussed in the aforementioned issue thread.

**Comment by betatim** [comment]
I'd be Ok with having a separate thread for topics/suggestions that are more speculative (and confine the discussion of that to that thread) instead of having it all in #2. We can tag them so that they are easy to find/ignore.

Closing issues to reduce clutter seems to be a delicate thing, at least in my experience it varies massively from project to project. My two cents: I like having things open because it makes them more visible in case someone has something to add and find the "cost" of having many open and currently stale threads not something that bothers me. -> We should experiment to get a feeling what works best for us.
